### ISSUE TITLE
最近12月网站上了反扒，有些账号签到会要求输入滑块验证码

### ISSUE THREAD

**Issue by yiqian987** [Chasing66/smzdm_bot#13]
最近12月网站上了反扒，有些账号签到会要求输入滑块验证
```
{
'error_code': 110202,
 'data': [],
 'error_msg': '验证码输入错误，请重新输入'
}
```

**Comment by Chasing66** [comment]
cookie还需要验证吗

**Comment by yiqian987** [comment]
> cookie还需要验证吗

cookie用过app的和网页的，都需要验证码。
我使用正常的浏览器签到是不需要的。

**Comment by RealBeBetter** [comment]
> > cookie还需要验证吗
> 
> cookie用过app的和网页的，都需要验证码。 我使用正常的浏览器签到是不需要的。 签到按钮按下去会先请求 https://zhiyou.smzdm.com/user/getgeetest/geetest_captcha_init 此链接初始化验证需要的geetest_challenge 所需参数 之后签到的地址多了入参 https://zhiyou.smzdm.com/user/checkin/jsonp_checkin geetest_challenge: 659d6a75ccd534e93a8729f6be58781eja geetest_validate: 9ea426a5c099c36b0a2b4c8099392726 geetest_seccode: 9ea426a5c099c36b0a2b4c8099392726|jordan

所以大佬们，这个问题可以通过请求多个接口解决吗？还是说这个项目基本废了？
有没有找到可用的解决办法？

**Comment by yduis6554** [comment]
> > > cookie还需要验证吗
> > 
> > 
> > cookie用过app的和网页的，都需要验证码。 我使用正常的浏览器签到是不需要的。 签到按钮按下去会先请求 https://zhiyou.smzdm.com/user/getgeetest/geetest_captcha_init 此链接初始化验证需要的geetest_challenge 所需参数 之后签到的地址多了入参 https://zhiyou.smzdm.com/user/checkin/jsonp_checkin geetest_challenge: 659d6a75ccd534e93a8729f6be58781eja geetest_validate: 9ea426a5c099c36b0a2b4c8099392726 geetest_seccode: 9ea426a5c099c36b0a2b4c8099392726|jordan
> 
> 所以大佬们，这个问题可以通过请求多个接口解决吗？还是说这个项目基本废了？ 有没有找到可用的解决办法？

所以，还是用AJ直接前端签到吧。

**Comment by yiqian987** [comment]
应该可以使用Selenium+dddd模拟滑块验证

**Comment by RealBeBetter** [comment]
> 所以，还是用AJ直接前端签到吧。

AJ 前端签到是什么？大佬能否讲讲？

**Comment by RealBeBetter** [comment]
> 应该可以使用Selenium+dddd模拟滑块验证

那目前这个就是直接废了呀，Selunium 这个有兴趣开发吗？只是我是写 Java 的，Python 太久没写估计废了

**Comment by Chasing66** [comment]
> > 所以，还是用AJ直接前端签到吧。
> 
> AJ 前端签到是什么？大佬能否讲讲？

他说的应该是Autojs吧

**Comment by RealBeBetter** [comment]
> 他说的应该是Autojs吧
大佬们会写这个吗？有什么需要协助的，或者有相关的想法，可以找我，我不想一直手动签到了。我都八百多天了，但是又不想断，呜呜呜~

**Comment by Chasing66** [comment]
> > 他说的应该是Autojs吧
> > 大佬们会写这个吗？有什么需要协助的，或者有相关的想法，可以找我，我不想一直手动签到了。我都八百多天了，但是又不想断，呜呜呜~

Autojs只能帮你打开app然后去签到，相当于手机端的Selenium, 并不能实现全自动化，例如定时去全自动出发，可能还需要其他软件配合，例如taskter

**Comment by Chasing66** [comment]
刚看了现在登录要验证了，确实是引入了验证机制
https://imgur.com/a/sY0S8Mx

**Comment by RealBeBetter** [comment]
> Autojs只能帮你打开app然后去签到，相当于手机端的Selenium, 并不能实现全自动化，例如定时去全自动出发，可能还需要其他软件配合，例如taskter

好的，我大概想起来了。是 Android 上的 Auto.js 自动触发脚本软件吧，但是目前用的是 iOS，好像目前对我而言没什么办法了~

**Comment by Chasing66** [comment]
> > Autojs只能帮你打开app然后去签到，相当于手机端的Selenium, 并不能实现全自动化，例如定时去全自动出发，可能还需要其他软件配合，例如taskter
> 
> 好的，我大概想起来了。是 Android 上的 Auto.js 自动触发脚本软件吧，但是目前用的是 iOS，好像目前对我而言没什么办法了~

是的，太局限了。上面说的是滑块认证，我自己尝试登录发现是图片选中认证 https://imgur.com/a/sY0S8Mx ，滑块认证比较简单，图片选中认证现在我暂时还没想到方法。

**Comment by Cyiming** [comment]
大佬们解决了踢我下

**Comment by Chasing66** [comment]
Fixed in commit: https://github.com/Chasing66/smzdm_bot/commit/ce3fa258af2cb9fa6f27914c19483477f495193b

https://github.com/Chasing66/smzdm_bot/issues/12
@Cyiming @RealBeBetter @yiqian987 
`User Agent`改为`iPhone`后貌似可以绕过去了，算是一个漏洞？
帮忙测试下，没多的账号，只测试了自己的账号。

**Comment by RealBeBetter** [comment]
> Fixed in commit: [ce3fa25](https://github.com/Chasing66/smzdm_bot/commit/ce3fa258af2cb9fa6f27914c19483477f495193b)
> 
> #12 @Cyiming @RealBeBetter @yiqian987 `User Agent`改为`iPhone`后貌似可以绕过去了，算是一个漏洞？ 帮忙测试下，没多的账号，只测试了自己的账号。

好的，感谢告知！看了大佬你的 commit，我是直接改成这个就好了吧：
`"Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) "
    "AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 "
    "Mobile/15E148 Safari/604.1 Edg/108.0.0.0"`

**Comment by Chasing66** [comment]
> > Fixed in commit: [ce3fa25](https://github.com/Chasing66/smzdm_bot/commit/ce3fa258af2cb9fa6f27914c19483477f495193b)
> > #12 @Cyiming @RealBeBetter @yiqian987 `User Agent`改为`iPhone`后貌似可以绕过去了，算是一个漏洞？ 帮忙测试下，没多的账号，只测试了自己的账号。
> 
> 好的，感谢告知！看了大佬你的 commit，我是直接改成这个就好了吧： `"Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) " "AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 " "Mobile/15E148 Safari/604.1 Edg/108.0.0.0"`


嗯，就改了个User-Agent

```
USER_AGENT = (
    "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) "
    "AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 "
    "Mobile/15E148 Safari/604.1 Edg/108.0.0.0"
)

"User-Agent": USER_AGENT,
```

**Comment by yiqian987** [comment]
> 上面说的是滑块认证，我自己尝试登录发现是图片选中认证 https://imgur.com/a/sY0S8Mx ，滑块认证比较简单，图片选中认证现在我暂时还没想到方法。

我的跑了qx的自动任务了，只能等明天，我也没有多余的账户。

**Comment by Chasing66** [comment]
> > 上面说的是滑块认证，我自己尝试登录发现是图片选中认证 https://imgur.com/a/sY0S8Mx ，滑块认证比较简单，图片选中认证现在我暂时还没想到方法。
> 
> 我的跑了qx的自动任务了，只能等明天，我也没有多余的账户。

应该暂时是可以用了，今天看到好多人fork的都成功跑起来了

**Comment by yiqian987** [comment]
done
