### ISSUE TITLE
建议增加额外奖励的request

### ISSUE THREAD

**Issue by kid1126** [Chasing66/smzdm_bot#25]
我抓了app的额外奖励的数据包，你加到脚本吧
import requests

headers = {
    'User-Agent': '',
    'request_key': '',
    'Cookie': '',
    'Content-Length': '95',
    'Host': 'user-api.smzdm.com',
    'Connection': 'Keep-Alive',
    'Accept-Encoding': 'gzip',
}

data = {
    'sign': 'AB1D963858B517E6FF6601AF80204162',
    'weixin': '0',
    'time': '16xxxxxxxx',
    'basic_v': '0',
    'f': 'android',
    'v': '10.4.26',
}

response = requests.post('https://user-api.smzdm.com/checkin/extra_reward', headers=headers, data=data)

但判断是否有额外奖励应该在https://user-api.smzdm.com/vip的res里标注，我没有对比过。建议能加上判断后再request会比较好

**Comment by gmdig** [comment]
readme里写的sk和token在哪找呢？我只能抓到ua和cookie

**Comment by Chasing66** [comment]
✅Implemented in 6cbec9245fc87c9809d494a1cae2730b49a89412
