### ISSUE TITLE
如果有多个号该怎么操作

### ISSUE THREAD

**Issue by xia1001** [Chasing66/smzdm_bot#27]
可以把CK分割开吗

**Comment by Chasing66** [comment]
GitHub action不是很适合拿来跑这种多账号的，它是从环境变量里获取配置，这种一个账号需要四个变量的就很麻烦了，暂时不打算支持。如果想要实现可以自己fork多个仓库自行配置。

本地运行的话可以运行多个docker。

**Comment by Chasing66** [comment]
本地运行已经支持多账号
