### ISSUE TITLE
小黄鸟抓不到SK

### ISSUE THREAD

**Issue by xuchjian** [Chasing66/smzdm_bot#28]
好像什么值得买改了，抓不到SK了

**Comment by colin2022** [comment]
第一次用。我就说怎么都找不到sk

**Comment by longwangjiang** [comment]
好着呢呀，我刚设置成功，sk有的。抓https://user-api.smzdm.com/checkin这个，里面所有信息都有。

**Comment by xuchjian** [comment]
> 好着呢呀，我刚设置成功，sk有的。抓[https://user-api.smzdm.com/checkin这个，里面所有信息都有。](https://user-api.smzdm.com/checkin%E8%BF%99%E4%B8%AA%EF%BC%8C%E9%87%8C%E9%9D%A2%E6%89%80%E6%9C%89%E4%BF%A1%E6%81%AF%E9%83%BD%E6%9C%89%E3%80%82)
说的有道理

**Comment by tangyanglai** [comment]
https://user-api.smzdm.com/checkin
app做什么动作才会调用这个接口呢？
ios我登录、随便点都没调用这个接口
