### ISSUE TITLE
请问下大佬，docker目录该怎么映射

### ISSUE THREAD

**Issue by xuchjian** [Chasing66/smzdm_bot#30]
上几个版本，都在环境里设置就行了，最新版本，环境里设置，说获取不到cookie，所以想问问大佬，能否给个目录映射，好方便改config

**Comment by Chasing66** [comment]
额，可能有个bug，等我修复吧

**Comment by Chasing66** [comment]
Fixed in f0c8d4f03cadeab27020b21b1f2c4a5611b86083
