### ISSUE TITLE
支持青龙吗？

### ISSUE THREAD

**Issue by qqhbc5918** [Chasing66/smzdm_bot#32]
可以适配下青龙吗

**Comment by jssimon007** [comment]
> 我基于本项目 Fork 了一版代码，可以支持青龙面板，并且增加了抽奖等功能，有兴趣可以试试 https://github.com/hex-ci/smzdm_script

感谢分享，可以做任务么？

**Comment by loveme1573** [comment]
> https://github.com/blackmatrix7/ios_rule_script/tree/master/script/smzdm
这里有签到+任务合一的 不知道为什么本地青龙运行不了 你可以参考一下

**Comment by loveme1573** [comment]
> > > 我基于本项目 Fork 了一版代码，可以支持青龙面板，并且增加了抽奖等功能，有兴趣可以试试 https://github.com/hex-ci/smzdm_script
> > 
> > 
> > 感谢分享，可以做任务么？
> 
> 目前已经支持做浏览和分享任务了，感谢关注。

https://github.com/blackmatrix7/ios_rule_script/tree/master/script/smzdm
这里有签到+任务合一的 不知道为什么本地和青龙运行不了 你可以参考一下

**Comment by loveme1573** [comment]
> > > > > 我基于本项目 Fork 了一版代码，可以支持青龙面板，并且增加了抽奖等功能，有兴趣可以试试 https://github.com/hex-ci/smzdm_script
> > > > 
> > > > 
> > > > 感谢分享，可以做任务么？
> > > 
> > > 
> > > 目前已经支持做浏览和分享任务了，感谢关注。
> > 
> > 
> > https://github.com/blackmatrix7/ios_rule_script/tree/master/script/smzdm 这里有签到+任务合一的 不知道为什么本地和青龙运行不了 你可以参考一下
> 
> 这个项目我看过，一些代码就是参考这里的，他这个项目好像不是用于青龙的。我的脚本里实现了APP里的任务，这个脚本的任务是 Web 端的，不太一样。抽奖我也已经实现了，收藏任务我感觉好像没啥用吧。

https://zhiyou.smzdm.com/user/tequan/    大把经验啊
<html>
<body>


行为类型 | 成长行为 | 单次获得经验值 | 每日最多获得经验值 | 碎银奖励 | 金币奖励 | 补充说明
-- | -- | -- | -- | -- | -- | --
内容互动 | 好价内容点值 | 3 | 15 | - | - | -
文章点赞、评论点赞 | 3 | 15 | - | - | -
收藏文章 | 8 | 40 | - | - | -
分享文章 | 5 | 25 | 每日首次奖励1碎银 | - | 活动期间还能获得不同奖励
发布评论 | 10 | 50 | 每日首次奖励1碎银 | - | 活动期间还能获得不同奖励
点击“直达链接” | 5 | 50 | - | - | 仅限APP端点击“直达链接”，“领券购买”按钮时发放经验值（PC端暂不支持），经验值次日发放


</body>
</html>

**Comment by loveme1573** [comment]
> > > > > > > 我基于本项目 Fork 了一版代码，可以支持青龙面板，并且增加了抽奖等功能，有兴趣可以试试 https://github.com/hex-ci/smzdm_script
> > > > > > 
> > > > > > 
> > > > > > 感谢分享，可以做任务么？
> > > > > 
> > > > > 
> > > > > 目前已经支持做浏览和分享任务了，感谢关注。
> > > > 
> > > > 
> > > > https://github.com/blackmatrix7/ios_rule_script/tree/master/script/smzdm 这里有签到+任务合一的 不知道为什么本地和青龙运行不了 你可以参考一下
> > > 
> > > 
> > > 这个项目我看过，一些代码就是参考这里的，他这个项目好像不是用于青龙的。我的脚本里实现了APP里的任务，这个脚本的任务是 Web 端的，不太一样。抽奖我也已经实现了，收藏任务我感觉好像没啥用吧。
> > 
> > 
> > https://zhiyou.smzdm.com/user/tequan/ 大把经验啊
> > 成长行为	单次获得经验值	每日最多获得经验值	碎银奖励	金币奖励	补充说明
> > 好价内容点值	3	15	-	-	-
> > 文章点赞、评论点赞	3	15	-	-	-
> > 收藏文章	8	40	-	-	-
> > 分享文章	5	25	每日首次奖励1碎银	-	活动期间还能获得不同奖励
> > 发布评论	10	50	每日首次奖励1碎银	-	活动期间还能获得不同奖励
> > 点击“直达链接”	5	50	-	-	仅限APP端点击“直达链接”，“领券购买”按钮时发放经验值（PC端暂不支持），经验值次日发放
> 
> 这些接口都需要研究，有时间可以看看。

https://github.com/Tsukasa007/my_script/blob/master/smzdm_mission.js  给你个我以前用的参考一下

**Comment by loveme1573** [comment]
> 



> > > > > > > > > 我基于本项目 Fork 了一版代码，可以支持青龙面板，并且增加了抽奖等功能，有兴趣可以试试 https://github.com/hex-ci/smzdm_script
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 感谢分享，可以做任务么？
> > > > > > > 
> > > > > > > 
> > > > > > > 目前已经支持做浏览和分享任务了，感谢关注。
> > > > > > 
> > > > > > 
> > > > > > https://github.com/blackmatrix7/ios_rule_script/tree/master/script/smzdm 这里有签到+任务合一的 不知道为什么本地和青龙运行不了 你可以参考一下
> > > > > 
> > > > > 
> > > > > 这个项目我看过，一些代码就是参考这里的，他这个项目好像不是用于青龙的。我的脚本里实现了APP里的任务，这个脚本的任务是 Web 端的，不太一样。抽奖我也已经实现了，收藏任务我感觉好像没啥用吧。
> > > > 
> > > > 
> > > > https://zhiyou.smzdm.com/user/tequan/ 大把经验啊
> > > > 成长行为	单次获得经验值	每日最多获得经验值	碎银奖励	金币奖励	补充说明
> > > > 好价内容点值	3	15	-	-	-
> > > > 文章点赞、评论点赞	3	15	-	-	-
> > > > 收藏文章	8	40	-	-	-
> > > > 分享文章	5	25	每日首次奖励1碎银	-	活动期间还能获得不同奖励
> > > > 发布评论	10	50	每日首次奖励1碎银	-	活动期间还能获得不同奖励
> > > > 点击“直达链接”	5	50	-	-	仅限APP端点击“直达链接”，“领券购买”按钮时发放经验值（PC端暂不支持），经验值次日发放
> > > 
> > > 
> > > 这些接口都需要研究，有时间可以看看。
> > 
> > 
> > https://github.com/Tsukasa007/my_script/blob/master/smzdm_mission.js 给你个我以前用的参考一下
> 
> 我看了一下这些应该都是 Web 的吧，应该还可以用吧？我看支持青龙？

对 这个得把cookie改成app端的还得把校验加上  还得再修改一下  才可以用  你看可以用吗

**Comment by loveme1573** [comment]
> > > 
> > 
> > 
> > > > > > > > > > > 我基于本项目 Fork 了一版代码，可以支持青龙面板，并且增加了抽奖等功能，有兴趣可以试试 https://github.com/hex-ci/smzdm_script
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 感谢分享，可以做任务么？
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 目前已经支持做浏览和分享任务了，感谢关注。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > https://github.com/blackmatrix7/ios_rule_script/tree/master/script/smzdm 这里有签到+任务合一的 不知道为什么本地和青龙运行不了 你可以参考一下
> > > > > > > 
> > > > > > > 
> > > > > > > 这个项目我看过，一些代码就是参考这里的，他这个项目好像不是用于青龙的。我的脚本里实现了APP里的任务，这个脚本的任务是 Web 端的，不太一样。抽奖我也已经实现了，收藏任务我感觉好像没啥用吧。
> > > > > > 
> > > > > > 
> > > > > > https://zhiyou.smzdm.com/user/tequan/ 大把经验啊
> > > > > > 成长行为	单次获得经验值	每日最多获得经验值	碎银奖励	金币奖励	补充说明
> > > > > > 好价内容点值	3	15	-	-	-
> > > > > > 文章点赞、评论点赞	3	15	-	-	-
> > > > > > 收藏文章	8	40	-	-	-
> > > > > > 分享文章	5	25	每日首次奖励1碎银	-	活动期间还能获得不同奖励
> > > > > > 发布评论	10	50	每日首次奖励1碎银	-	活动期间还能获得不同奖励
> > > > > > 点击“直达链接”	5	50	-	-	仅限APP端点击“直达链接”，“领券购买”按钮时发放经验值（PC端暂不支持），经验值次日发放
> > > > > 
> > > > > 
> > > > > 这些接口都需要研究，有时间可以看看。
> > > > 
> > > > 
> > > > https://github.com/Tsukasa007/my_script/blob/master/smzdm_mission.js 给你个我以前用的参考一下
> > > 
> > > 
> > > 我看了一下这些应该都是 Web 的吧，应该还可以用吧？我看支持青龙？
> > 
> > 
> > 对 这个得把cookie改成app端的还得把校验加上 还得再修改一下 才可以用 你看可以用吗
> 
> 应该只是签到失效了吧，其他的都是用的 Web 接口，Web 接口只有签到加了验证码吧，你试过除了签到以外的功能吗？

web端签到必黑 让修改密码    取消了签到   任务可以正常做   不知道不加校验 cookie能用多久

**Comment by Chasing66** [comment]
qinglong is now supported in commit 49192317a8b98c9135c59ffb3f953764dac988a3
