### ISSUE TITLE
请问Build image出现问题

### ISSUE THREAD

**Issue by lordleonli** [Chasing66/smzdm_bot#34]
![无标题](https://user-images.githubusercontent.com/74086662/222883846-70285db9-5acd-4faa-90a0-14d11d728622.png)

**Comment by Chasing66** [comment]
加两个secret
`DOCKERHUB_TOKEN` 和 `DOCKERHUB_USERNAME`

**Comment by Chasing66** [comment]
实际上只需要修改.github/workflows/checkin.yml 就好了，并不需要你自己build 镜像
