### ISSUE TITLE
SK是啥，抓的包里没找到

### ISSUE THREAD

**Issue by sunopen1979** [Chasing66/smzdm_bot#37]
SK是啥，抓的包里没找到，cookie是全部都复制吗？

**Comment by Remoyang** [comment]
3月27日，request data里没看见SK这个键

**Comment by Chasing66** [comment]
https://user-api.smzdm.com/checkin -> 请求 -> 右下角预览  -> 第五项 sk=xxxx
@Remoyang @sunopen1979 

> 3月27日，request data里没看见SK这个键

**Comment by Remoyang** [comment]
水果手机，没有HttpCanary，用了Stream抓的包参数都没有SK （0.0）

**Comment by Microbai** [comment]
vmos抓的包没有sk

**Comment by Chasing66** [comment]
> vmos抓的包没有sk

我刚刚才试了下，是能抓到的

**Comment by Chasing66** [comment]
SK 不是必填值， 可以只设置`ANDROID_COOKIE`
Solved in 764606bb7e2448c2e91cddff4cc6b021860cdae2
