### ISSUE TITLE
貌似签到奖励无法自动领取

### ISSUE THREAD

**Issue by Botree-Chan** [Chasing66/smzdm_bot#39]
只能签到，无法领取签到奖励，大家也这样么？

**Comment by Chasing66** [comment]
好像是有这个bug，不过目前没有时间和精力修复。。。

**Comment by anycallma** [comment]
http://zdmclock.bitup.top/#/pages/smzdm/userclock?id=4079?id=15465
这个站可以自动签到,我试了好几天了
