### ISSUE TITLE
大佬，青龙拉库命令不对鸭

### ISSUE THREAD

**Issue by QiWu666** [Chasing66/smzdm_bot#47]
小白，复制教程里面的拉库地址[![p9IxiZR.jpg](https://s1.ax1x.com/2023/05/22/p9IxiZR.jpg)](https://imgse.com/i/p9IxiZR)，运行smzdm_ql.py时，显示[![p9IxkIx.jpg](https://s1.ax1x.com/2023/05/22/p9IxkIx.jpg)](https://imgse.com/i/p9IxkIx)，不知道怎么改

**Comment by Chasing66** [comment]
在订阅管理页面里新建订阅。订阅完成后会自动在定时任务页面创建任务

**Comment by QiWu666** [comment]
我的是2.11.3旧版青龙，没有订阅管理页面，都是在定时任务里面的新建任务里面去拉库。感谢老哥

**Comment by enwaiax** [comment]
用新版本的呗

**Comment by yunzimo** [comment]
> 我的是2.11.3旧版青龙，没有订阅管理页面，都是在定时任务里面的新建任务里面去拉库。感谢老哥

他这个目录都写死了，是不兼容旧版青龙的，除非你自己拉下来改改代码。2.12往上目录就不一样了
