### ISSUE TITLE
青龙容器报错Running pip as the 'root' 

### ISSUE THREAD

**Issue by leave668** [Chasing66/smzdm_bot#48]
## 开始执行... 2023-05-28 09:34:27

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2023-05-28 09:34:28.074 | INFO     | __main__:load_conf:37 - Please set cookies first

## 执行结束... 2023-05-28 09:34:28  耗时 1 秒

**Comment by enwaiax** [comment]
wanring 没关系的，你的报错是没有设置cookies

**Comment by leave668** [comment]
哦，CK是测试的。报错没关系的话  那就没事了。
