### ISSUE TITLE
检测不到tg bot的反向代理网址

### ISSUE THREAD

**Issue by 88484396** [Chasing66/smzdm_bot#52]
平台是青龙面板，用的tg bot，京东脚本和阿里云正常通知，什么值得买没有通知，查看日志有这么一段：
notify.notify:tg_bot:105 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url
这应该还是用的官方api吧，应该是没检测到的原因？这个要怎么办？

**Comment by enwaiax** [comment]
偶尔遇到发不出的问题，应该是个bug，不过目前还没有时间去debug
