### ISSUE TITLE
青龙面板的环境变量应该怎么填写呀？

### ISSUE THREAD

**Issue by silouhette** [Chasing66/smzdm_bot#57]
如题

**Comment by enwaiax** [comment]
跟正常使用变量一样，或者参考：
https://github.com/Chasing66/smzdm_bot#31-%E9%9D%92%E9%BE%99%E9%9D%A2%E6%9D%BF

**Comment by silouhette** [comment]
您好，感谢回复，我的意思是没明白环境变量的名称和值应该具体填写什么。
![image](https://github.com/Chasing66/smzdm_bot/assets/51879388/43f3774c-4135-472e-bcfd-ccb1a8dcaee3)

**Comment by silouhette** [comment]
是不是值填写抓到的cookie，那名称是随意填写嘛，还是有什么特殊的要求，麻烦您解惑一下。

**Comment by enwaiax** [comment]
需要使用这些作为名称关键字
https://github.com/Chasing66/smzdm_bot#21-%E4%BB%8E%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E4%B8%AD%E8%AF%BB%E5%8F%96%E9%85%8D%E7%BD%AE

**Comment by silouhette** [comment]
ok，已经成功啦，感谢您的回复。
