### ISSUE TITLE
定时启动不好用？

### ISSUE THREAD

**Issue by jiaoting** [Chasing66/smzdm_bot#9]
![image](https://user-images.githubusercontent.com/12553424/202600833-15bc4005-9ecb-4ab3-b091-bdcf34e61da9.png)
为啥我这样设定，不会定时启动呢？

**Comment by Chasing66** [comment]
很明显语法不对， 建议先去查一下crontab语法
例如， `cron: "0 23 * * *"` 表示utc时间的每天18点触发定时任务，也就是北京时间早上7点
